name: MacOS

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: install

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-dependencies

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/${{ env.INSTALL_LOCATION }}"

      - name: Build
        run: cmake --build build --config $BUILD_TYPE -j

      - name: Run Tests
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: install project
        run: cmake --build build --target install --config Release
