name: Windows

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: "install"

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}
          key: ${{runner.os}}-dependencies

      # - name: install GoogleTest
      #   if: ${{steps.cache.output.cache-hit != 'true'}}
      #   run: |
      #     cd ..
      #     git clone https://github.com/google/googletest.git --branch release-1.10.0
      #     cd googletest
      #     cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/$env:INSTALL_LOCATION" -Dgtest_force_shared_crt=1
      #     cmake --build build --config Release
      #     cmake --build build --target install --config Release
      #     cd ../modern-cpp-template

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/${{ env.INSTALL_LOCATION }}"

      - name: Build
        run: cmake --build build --config "$env:BUILD_TYPE" -j

      - name: Run Tests
        working-directory: build
        run: ctest -C "$env:BUILD_TYPE"

      - name: Install Project
        run: cmake --build build --target install --config Release
